from threading import TIMEOUT_MAX

import utils

# Global Variables

OBSTACLE_HEIGHT = 20
NUM_SPIRAL_POINTS = 200

GENERATION_AREA_MIN_POS = utils.Position(-40,10)
GENERATION_AREA_MAX_POS = utils.Position(30,40)

OBST_MIN_LENGTH = 10
OBST_MIN_WIDTH = 10
OBST_MAX_WIDTH = 20
OBST_MAX_LENGTH = 20
OBST_MIN_HEIGHT = 15
OBST_MAX_HEIGHT = 25

THRESHOLD_DISTANCE = 20

DIR_GENERATED_PLOTS = "generated_tests_plot/"

SPIRAL_GOLDEN_ANGLE = 0.1 
SPIRAL_RADIUS_INCREMENT = 0.02
SPIRAL_NUM_POINTS = 30

TESTS_FOLDER = "./generated_tests/"

TIMEOUT_MAX = 600

MIN_DISTANCE_TO_SAVE = 5